feature/#2/domain,repository생성
Leets-Official/Leets-Garden-BE pull request #2
Opened 2023-11-20 12:58 UTC by hyunnniii

## 1. 무슨 이유로 코드를 변경했나요?
Repository와 Domain파일의 Entity 생성하였습니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
프로젝트 시작 단계로 아직 위험이나 장애를 발견하지 못했습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항
- 기획한 DB 바탕으로 4개의 테이블에 해당하는 Entity 생성하였습니다.

- 구상에 맞는 Repository(user, meeting, attentance 생성하였습니다
<br>

## 5. 추가 사항
entity 속성 값이나 매핑 검토해주세요
Authority의 entity가 아직 생성되지 않았습니다. 빠른 시일 내에 추가하도록 하겠습니다.

2023-11-21 05:27 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private String user_id;
카멜 케이스로 변경하는 것이 어떨까요?

2023-11-21 05:27 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/domain/User.java
> +@Entity(name = "user")
mysql의 예약어와 충돌할까봐 entity명을 지으셨다면 users가 더 낫지 않을까요?

2023-11-21 05:27 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/repository/AttendanceRepository.java
> +
@Repository 어노테이션을 추가하는 것이 어떨까요?

2023-11-21 05:31 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/repository/AttendanceRepository.java
> +public interface AttendanceRepository extends JpaRepository<Attendance, Long> {
@Repository 어노테이션을 추가하는 것이 어떨까요?

2023-11-21 10:41 UTC, rootTiket commented on src/main/java/com/example/leetsgarden/repository/AttendanceRepository.java
> +public interface AttendanceRepository extends JpaRepository<Attendance, Long> {
@repository 어노테이션은 jparepository를 상속 받을 경우 사용하지 않는 것으로 알고 있습니다!

2023-11-21 16:00 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/repository/AttendanceRepository.java
> +public interface AttendanceRepository extends JpaRepository<Attendance, Long> {
헉 그렇네요. 감사합니다!

2023-11-21 16:11 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private String user_id;
카멜 케이스로 변경하는 것이 어떨까요?

2023-11-22 04:25 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private String user_id;
네!수정하겠습니다.

2023-11-22 04:40 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/User.java
> +@Entity(name = "user")
네! 수정하겠습니다

2023-11-22 05:13 UTC, rootTiket commented
문제 없는 것 같습니다.

2023-11-22 05:18 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private List<Meeting> meetingList;
meetingList가 좋을까요? 미팅 도메인에선 users라고 되어있긴하던데 meetings는 어떤가요?

2023-11-22 05:18 UTC, rootTiket approved these changes

2023-11-22 05:35 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private List<Meeting> meetingList;
userList, meetingList로 변경해도 좋을 거 같습니다.

2023-11-22 05:36 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private List<Meeting> meetingList;
네 그렇게 통일해도 좋을것같습니다.

2023-11-22 05:50 UTC, jwnnoh requested changes

2023-11-22 05:50 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/domain/Attendance.java
> +    @Column(unique = true)
각 동아리원이 속한 스터디/정기모임에 대한 참석여부를 `boolean` 타입으로 설정해주신 것 같은데, 해당 Column은 저장될 수 있는 값이 true,false 두 가지 경우밖에 없어 논리적으로 `unique`가 될 수 없을 것 같습니다.

2023-11-22 05:50 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @Column
장소가 DB에 저장되어야 할 이유가 있을까요? 장소가 유동적으로 변경되는 경우가 많은 것으로 알 고 있습니다.

2023-11-22 05:50 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/domain/User.java
통상적으로 로그인할 때 쓰이는 Id는 `username`으로 작성되고는 합니다. 저희는 이번에 학번을 통해 로그인을 구현할 예정이니 해당 부분에 대한 적절한 수정이 필요할 것 같습니다. 또한, 닉네임같은 경우는 고려해주지 않고 실명을 사용하는게 낫지 않을까요?

2023-11-22 05:52 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @Column
유동적으로 변경되기때문에 모임 생성할때마다 값을 넣도록 해야하는 것 아닌가요? :D

2023-11-22 05:54 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/User.java
실명 속성도 있기는한데 그때 회의할때 닉넴도 추가하면 어떨까하고 일단 넣는 방식으로 얘기 했었습니다. 닉네임 속성이 일단 불필요한것 같긴 합니다.

2023-11-22 05:55 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private List<Meeting> meetingList;
방법 고민하고 있었는데 좋은 생각입니다! 수정하겠습니다

2023-11-22 05:59 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @Column
제가 생각한 로직은 처음 Meeting이 생성되었을 때의 값이 불변하게 유지되는 것이었습니다. 결국 서비스는 사용자가 어떠한 Meeting을 출석했냐가 관건이라고 생각했기에, 굳이 Meeting의 장소를 고려할 필요는 없다고 생각하였습니다.

2023-11-22 06:13 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @ManyToMany(mappedBy = "meeting", fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
옵션을 `fetch = FetchType.EAGER, cascade = CascadeType.REMOVE` 로 지정한 이유가 있나요?

2023-11-22 06:15 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/Attendance.java
> +    @Column(unique = true)
네네 감사합니다! 수정하였습니다

2023-11-22 06:21 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @Column
관리자가 <update: 정기 모임 및 스터디의 세부 사항을 수정>할 수 있기 때문에 값이 변했을 때 반영할 수 있습니다. 
장소에 관한 부분은 초기 DB설계의 변화이기 때문에 팀원과 같이 논의해보면 좋을 것 같습니다.

2023-11-22 06:28 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/User.java
닉네임은 주 기능과 별 개의 부가적인 요소입니다.
부가적인 부분이니 추후 필요 시 추가하는 방향으로 하겠습니다.

2023-11-22 06:36 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @ManyToMany(mappedBy = "meeting", fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
1. fetch = FetchType.EAGER의 이유
 관련된 'User' 엔티티들이 즉시 로딩할 수 있도록 지정하기 위함입니다. 
 즉, 'Meeting' 엔티티를 조회할 때, 관련된 'User'엔티티도 함께 로딩됩니다. 
2. cascade = CascadeType.REMOVE의 이유
 'Meeting' 엔티티가 삭제될 때 연결된 'User'엔티티도 함께 삭제할 수 있도록 지정하기 위함입니다.
 'Meeting'을 삭제하면 해당 회의에 참여하고 있는 참석자들도 함께 삭제됩니다.

2023-11-22 06:39 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @ManyToMany(mappedBy = "meeting", fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
즉시 로딩의 경우 N+1 문제가 발생할 수 있습니다. 이 부분은 팀원들과 상의하면 좋을 것 같아요~

Meeting을 삭제해도 회원은 유지해야 하지 않나요? 일회성 회원인가요?

2023-11-22 06:54 UTC, hyunnniii commented on src/main/java/com/example/leetsgarden/domain/Meeting.java
> +    @ManyToMany(mappedBy = "meeting", fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
그렇네요! 각 스터디의 유저가 삭제되어야 한다고 착각했네요! 
수정하겠습니다 감사합니다!

2023-11-22 07:12 UTC, jwnnoh approved these changes
고생하셨습니다.

2023-11-22 07:13 UTC, merged