[Feat] #5 로그인 회원가입 제작
Leets-Official/Leets-Garden-BE pull request #7
Opened 2023-11-25 16:13 UTC by taeseokyang

## 1. 무슨 이유로 코드를 변경했나요?

스프링 시큐리티, jwt관련 코드와 로그인, 회원가입 로직을 추가하였습니다.

API는 로그인 API, 회원가입 API, 회원 조회 API 총 3개 추가 되었으며,
기존 meeting 코드와 호환되도록 수정하였습니다.

## 2. 어떤 위험이나 장애를 발견했나요?

일부 에러는 엔티티의 어노테이션 문제였습니다. 알맞게 변경하였습니다.

## 3. 관련 스크린샷을 첨부해주세요.

### 회원 조회 결과
<img width="438" alt="Screenshot 2023-11-26 at 1 01 54 AM" src="https://github.com/Leets-Official/Leets-Garden-BE/assets/136783693/77f1d1b7-7fc2-4c53-81ba-32fd3f43e057">

### 미팅 조회 결과
<img width="419" alt="Screenshot 2023-11-26 at 1 00 26 AM" src="https://github.com/Leets-Official/Leets-Garden-BE/assets/136783693/cedfb5b4-39fd-4f9e-931f-dc66ee0b64c9">

## 4. 완료 사항

로그인, 회원가입

## 5. 추가 사항

현재 권한 종류는 user와 admin 2개입니다. 추후 권한을 세분화 하고, api 접근 권한 코드를 추가하겠습니다.

2023-11-25 17:27 UTC, anxi01 requested changes

2023-11-25 17:27 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/dto/request/SignRequest.java
> +@Setter
@Setter 대신 생성자를 이용하거나 빌더 패턴을 이용하는게 좋을 거 같아요!

2023-11-25 17:27 UTC, anxi01 commented on src/main/java/com/example/leetsgarden/service/MeetingService.java
> +            User user = userRepository.findByUserId(userName).orElseThrow(() -> new IllegalArgumentException("해당 User는 존재하지 않습니다."));
요청 값에 참여자 이름 리스트가 들어가서 findByName()으로 했던 건데 userId로 바꾸신 이유가 있을까요??

2023-11-26 01:33 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/service/MeetingService.java
> +            User user = userRepository.findByUserId(userName).orElseThrow(() -> new IllegalArgumentException("해당 User는 존재하지 않습니다."));
속성중에 name과 userid둘다 있는데 저기서 사용하는건 userid기 때문에 저렇게 바꾸는게   명시적이고 혼선이 없을거 같아서 입니다

2023-11-26 01:39 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/controller/SignController.java
`SignController`이라는 파일명을 조금 더 직관적이게 `UserController`로 변경하는건 어떤가요?

2023-11-26 01:39 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/controller/SignController.java
> +}
`getUser` 과 `getUserForAdmin`  로직이 동일한데, 해당 부분을 따로 `SignService`에서 처리해주는건 어떨까요?

2023-11-26 01:39 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/domain/User.java
>      @Column(nullable = false)
`userId` 와 `id` 의 역할이 작명으로 인해 헷갈리는 것 같습니다. 변수명을 달리 하는것을 고려해봐도 좋을 것 같습니다.

2023-11-26 01:39 UTC, jwnnoh commented on src/main/java/com/example/leetsgarden/service/SignService.java
클래스에 `Transactional` 어노테이션 적용시, 전체 메서드에 적용되므로 모든 메서드마다 개별 어노테이션을 달아줄 필요는 없을 것 같습니다.

2023-11-26 02:33 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/controller/SignController.java
좋은것 같습니다. 기존 DTO, 컨트롤러, 서비스 모두 Sign~~ -> User~~ 로 변경하였습니다

2023-11-26 02:40 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/User.java
>      @Column(nullable = false)
맞습니다. 비슷하기는 하나 코드에서 실사용하는 변수는 userId 뿐이라 큰 착오를 가져올거라 생각하지 않습니다. 또한 적절한 이름을 찾지 못하겠습니다. username으로 해도 name 속성과 겹칠 것 같습니다. id는 자동증가 인덱스 속성, userid는 로그인 아이디 속성임에 대한 의미를 잘 가지고 있다 생각합니다.

2023-11-26 02:48 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/service/SignService.java
넵 수정했습니다!

2023-11-26 02:52 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/controller/SignController.java
> +}
지금 생각해 보면 애초에 관리자를 위한 유저 조회 api를 구분할 필요 없다 생각이 듭니다. 조회는 제한하지 않고, 미팅 생성 수정 같은 일등을 어드민만 가능하게 제한 하게 하는게 어떤가요? 이렇게 한다면 위 컨트롤러는 삭제하겠습니다.

2023-11-26 02:58 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/dto/request/SignRequest.java
> +@Setter
애초애 세터가 필요 없었던것 같습니다!

2023-11-26 03:05 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/User.java
>      @Column(nullable = false)
username으로 수정하였습니다

2023-11-26 03:23 UTC, jwnnoh approved these changes
고생하셨습니다.

2023-11-26 04:07 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/service/UserService.java
> +        if (userRepository.countUserByUsername(request.getUsername())==1){
JPA 메서드에 `exist` 가 있는데 `count`로 회원 여부를 판단한 이유가있나용?

2023-11-26 04:07 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/service/UserService.java
> +        }else{
위에서 경우마다 early return을 해줘서 else 는 없는게 더 깔끔할 것 같아용

2023-11-26 04:07 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private List<Authority> roles = new ArrayList<>();
권한을 list로 둔 이유가 있나용?

2023-11-26 04:56 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/dto/response/RegisterResponse.java
> +    }
Builder 나 AllArgsConstructor로 대체가능할 것 같아오

2023-11-26 04:56 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/security/JwtProvider.java
> +    private final long exp = 1000L * 60 * 60;
상수라면 static 추가해주세용 그리고 상수명는 UPPERCASE 입니다

2023-11-26 04:56 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/security/JwtProvider.java
> +            if (!token.substring(0, "BEARER ".length()).equalsIgnoreCase("BEARER ")) {
하드코딩보다는 상수로 관리하는 게 좋아요~

2023-11-26 04:56 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/security/JwtProvider.java
> +            }
이부분도 `else` 처리하지 않아도 됩니당

2023-11-26 04:56 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/service/UserService.java
> +            }
if문에서 유저가 이미 존재할 때를 예외처리하는 게 더 깔끔할 것 같아요

2023-11-26 05:53 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/User.java
미팅 엔티티 조회 결과에 유저 정보도 들어가는데, 모든 정보가 들어가니 보기 안좋아서 유저 네임 빼고 해당 어노테이션 추가했습니다, 유저 네임만 필요 할것 같아서요. 이후 필요한 속성이 있으면 삭제하고자 했습니다.

그래서 위 사진을 보시면 유저 정보에 userid만 있습니다. 더 깔끔한것 같습니다

2023-11-26 06:03 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/controller/UserController.java
> +    @GetMapping("/user/get")
넵 수정했습니다!

2023-11-26 06:04 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/service/UserService.java
> +        if (userRepository.countUserByUsername(request.getUsername())==1){
없습니다! exist를 몰랐습니다. 수정하겠습니다

2023-11-26 06:31 UTC, ay-eonii commented on src/main/java/com/example/leetsgarden/domain/User.java
음 미팅 조회 시 유저 정보 전체가 필요없다면 dto를 새로 생성해서 필요한 데이터만 보내는 게 좋을 것 같아요. 현재 미팅에 attedanceList가 있어서 위 사진처럼 meeting을 조회하면 attendacne에서 미팅 정보가 중복으로 조회되고 있어요. 이러면 모든 곳에 미팅에도 `@JsonIgnore`을 사용해야 하는데, 이보다 미팅 조회 시 미팅을 참조하고 있는 attendacne를 attendance Reposiroty에서 따로 조회하고 두 정보를 dto로 묶어 보내는 방법은 어떤가요?

사실 이 부분은 제가 api 명세를 못봐서 어떤 경우 필요한 api 인지 잘 모르겠습니다. 팀원들과 상의 후에 meeting의 attendance만 조회하는 api를 따로 만드는 것도 하나의 방법일 것 같아요.

2023-11-26 09:01 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/service/UserService.java
> +        }else{
아 그러네요! 수정했습니다

2023-11-26 09:03 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/dto/response/RegisterResponse.java
> +    }
오.. 수정했습니다

2023-11-26 09:06 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/domain/User.java
> +    private List<Authority> roles = new ArrayList<>();
이 부분에 대해서 상의한 내용을 토대로 고민해보겠습니다

2023-11-26 09:07 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/security/JwtProvider.java
> +            }
넵 수정했습니다.

2023-11-26 09:10 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/service/UserService.java
> +            }
넵 수정했습니다

2023-11-26 10:00 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/security/JwtProvider.java
> +    private final long exp = 1000L * 60 * 60;
넵 수정하였습니다.

2023-11-26 10:02 UTC, taeseokyang commented on src/main/java/com/example/leetsgarden/security/JwtProvider.java
> +            if (!token.substring(0, "BEARER ".length()).equalsIgnoreCase("BEARER ")) {
무슨말씀이신가요? 이해가 안됩니다!

2023-11-26 13:09 UTC, ay-eonii approved these changes
확인했습니다~

2023-11-26 13:13 UTC, anxi01 approved these changes

2023-11-26 13:58 UTC, merged